# GitHub Actions workflow for pipeline monitoring.

# This workflow provides a one click end to end execution of data pipeline
#using github actions.It runs full ingestion,transformation, and loading,followed
#by monitoring checks to ensure data quality.
#This allows reproducible pipeline execution without local setup.
#It allows pipeline to be triggered manually from github.
#Helps to generate monitoring reports for data quality validation.



name: Pipeline Monitoring

on:
  workflow_dispatch:

jobs:
  pipeline-monitor:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p${{ secrets.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: 127.0.0.1
      DB_PORT: "3306"
      DB_NAME: ${{ secrets.DB_NAME }}
      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASSWORD -e "SELECT 1" $DB_NAME && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Create schema tables
        run: |
          mysql -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASSWORD $DB_NAME < sql/01_create_tables.sql

      - name: Run pipeline
        run: |
          python run_pipeline.py

      - name: Run monitoring checks
        run: |
          python monitoring/run_monitoring.py

      - name: Upload monitoring report artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitoring-report
          path: monitoring/reports/monitoring_report.txt

      # TODO - Create a steamlit app to visualize the monitoring report
      # - name: Deploy to Streamlit
      #   uses: streamlit/streamlit-app-action@v0.0.3
      #   with:
      #     app-path: streamlit_app.py
